name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch: # Магическая кнопка ручного запуска
  push:
    tags:
      - 'v*.*'       # Включает v2.7, v2.7-beta
      - '!v*.*.*'    # ИСКЛЮЧАЕТ патчи вроде v2.7.1

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # СТРОГОЕ УСЛОВИЕ (AND): Запускать только если это ручной запуск ИЛИ тег был пушнут именно в ветку main
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'push' && github.event.base_ref == 'refs/heads/main')
    
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:${{ github.ref_name }}-sha-${{ github.sha }}